### ISSUE TITLE
Getting Error when running serve in flap-freny.

### ISSUE THREAD

**Issue by vatsilidis** [meta-quest/webxr-showcases#3]
While I'm running  the 4th step "npm run serve" in the flap-frenzy folder I'm getting the following error:

npm run serve

> serve
> webpack serve

<i> [webpack-dev-server] SSL certificate: /Users/User1/Desktop/Meta/WebXR/webxr-showcases/flap-frenzy/node_modules/.cache/webpack-dev-server/server.pem
/Users/User1/Desktop/Meta/WebXR/webxr-showcases/flap-frenzy/node_modules/webpack-dev-server/lib/Server.js:2585
        throw error;
        ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:8081
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at doListen (node:net:2014:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8081
}

Node.js v18.18.2

**Comment by felixtrz** [comment]
> Error: listen EADDRINUSE: address already in use 0.0.0.0:8081

This error is because you are running something else on port 8081, you can either stop the other processes using port 8081, or change the devserver config to have flap frenzy be served on another port, for example, 8082
